version '3.6'

services:
  # MySql
 db:
   image: mysql:8.0
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: covid19db
     MYSQL_USER: user
     MYSQL_PASSWORD: user

  ports:
  - '3306:3306'

  volumes:
  - ./init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  covid19-main:
    image: kkapelon/covid19-mysql
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8085:8085
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=user
      - DATABASE_NAME=covid19db
      - DATABASE_PORT=3306